/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Enseignant;

/**
 *
 * @author Hachem
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel1 = new javax.swing.JPanel();
        panel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel12 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel16 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jPanel17 = new javax.swing.JPanel();
        jLabel16 = new javax.swing.JLabel();
        jPanel18 = new javax.swing.JPanel();
        jLabel17 = new javax.swing.JLabel();
        jPanel19 = new javax.swing.JPanel();
        jLabel18 = new javax.swing.JLabel();
        diplome = new javax.swing.JLabel();
        cin = new javax.swing.JLabel();
        prenom = new javax.swing.JLabel();
        nom = new javax.swing.JLabel();
        adresse = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jPanel8 = new javax.swing.JPanel();
        jLabel7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        jLabel8 = new javax.swing.JLabel();
        login = new javax.swing.JTextField();
        newPassword = new javax.swing.JPasswordField();
        jPanel10 = new javax.swing.JPanel();
        jLabel9 = new javax.swing.JLabel();
        oldPassword = new javax.swing.JPasswordField();
        validerPassword = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel5 = new javax.swing.JLabel();
        validerTheme = new javax.swing.JButton();
        combo = new javax.swing.JComboBox();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel1.setBackground(new java.awt.Color(204, 204, 255));
        panel1.setLayout(null);

        panel2.setBackground(new java.awt.Color(0, 0, 204));
        panel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        panel2.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Parametre");
        panel2.add(jLabel1);
        jLabel1.setBounds(170, 0, 230, 40);

        panel1.add(panel2);
        panel2.setBounds(0, 0, 780, 40);

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(51, 51, 0));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setForeground(new java.awt.Color(51, 51, 0));
        jPanel2.setLayout(null);

        jLabel4.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel4.setText("Profile");
        jPanel2.add(jLabel4);
        jLabel4.setBounds(20, 0, 230, 40);

        jPanel1.add(jPanel2);
        jPanel2.setBounds(0, 0, 320, 40);

        jPanel12.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Adresse");
        jPanel12.add(jLabel10);
        jLabel10.setBounds(0, 0, 140, 50);

        jPanel1.add(jPanel12);
        jPanel12.setBounds(10, 250, 160, 50);

        jPanel16.setLayout(null);

        jLabel11.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Diplome");
        jPanel16.add(jLabel11);
        jLabel11.setBounds(0, 0, 140, 50);

        jPanel1.add(jPanel16);
        jPanel16.setBounds(10, 320, 160, 50);

        jPanel17.setLayout(null);

        jLabel16.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel16.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel16.setText("Cin");
        jPanel17.add(jLabel16);
        jLabel16.setBounds(0, 0, 80, 50);

        jPanel1.add(jPanel17);
        jPanel17.setBounds(10, 70, 160, 50);

        jPanel18.setLayout(null);

        jLabel17.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Prenom");
        jPanel18.add(jLabel17);
        jLabel17.setBounds(0, 0, 130, 50);

        jPanel1.add(jPanel18);
        jPanel18.setBounds(10, 130, 160, 50);

        jPanel19.setLayout(null);

        jLabel18.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel18.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel18.setText("Nom");
        jPanel19.add(jLabel18);
        jLabel18.setBounds(0, 0, 90, 50);

        jPanel1.add(jPanel19);
        jPanel19.setBounds(10, 190, 160, 50);

        diplome.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        diplome.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(diplome);
        diplome.setBounds(170, 320, 140, 50);

        cin.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        cin.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(cin);
        cin.setBounds(170, 70, 140, 50);

        prenom.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        prenom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(prenom);
        prenom.setBounds(170, 130, 140, 50);

        nom.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        nom.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(nom);
        nom.setBounds(170, 190, 140, 50);

        adresse.setFont(new java.awt.Font("Yu Gothic Light", 1, 18)); // NOI18N
        adresse.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jPanel1.add(adresse);
        adresse.setBounds(170, 250, 140, 50);

        panel1.add(jPanel1);
        jPanel1.setBounds(0, 50, 320, 400);

        jPanel3.setBackground(new java.awt.Color(204, 51, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(153, 0, 153));
        jPanel4.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel4.setLayout(null);

        jLabel6.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Changer password ");
        jPanel4.add(jLabel6);
        jLabel6.setBounds(0, 0, 400, 40);

        jPanel3.add(jPanel4);
        jPanel4.setBounds(0, 0, 450, 40);

        jPanel8.setLayout(null);

        jLabel7.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Login");
        jPanel8.add(jLabel7);
        jLabel7.setBounds(0, 0, 90, 30);

        jPanel3.add(jPanel8);
        jPanel8.setBounds(20, 50, 200, 30);

        jPanel9.setLayout(null);

        jLabel8.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel8.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel8.setText("New Password");
        jPanel9.add(jLabel8);
        jLabel8.setBounds(0, 0, 170, 30);

        jPanel3.add(jPanel9);
        jPanel9.setBounds(20, 130, 200, 30);
        jPanel3.add(login);
        login.setBounds(250, 50, 150, 30);
        jPanel3.add(newPassword);
        newPassword.setBounds(250, 130, 150, 30);

        jPanel10.setLayout(null);

        jLabel9.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel9.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel9.setText("Old Password");
        jPanel10.add(jLabel9);
        jLabel9.setBounds(0, 0, 170, 30);

        jPanel3.add(jPanel10);
        jPanel10.setBounds(20, 90, 200, 30);
        jPanel3.add(oldPassword);
        oldPassword.setBounds(250, 90, 150, 30);

        validerPassword.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        validerPassword.setText("Valider");
        validerPassword.setBorder(null);
        jPanel3.add(validerPassword);
        validerPassword.setBounds(110, 170, 220, 40);

        panel1.add(jPanel3);
        jPanel3.setBounds(330, 50, 450, 230);

        jPanel5.setBackground(new java.awt.Color(204, 51, 255));
        jPanel5.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel5.setLayout(null);

        jPanel6.setBackground(new java.awt.Color(153, 0, 153));
        jPanel6.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel6.setLayout(null);

        jLabel5.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Choisir votre Theme ");
        jPanel6.add(jLabel5);
        jLabel5.setBounds(80, 0, 250, 40);

        jPanel5.add(jPanel6);
        jPanel6.setBounds(0, 0, 450, 40);

        validerTheme.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        validerTheme.setText("Valider");
        validerTheme.setBorder(null);
        jPanel5.add(validerTheme);
        validerTheme.setBounds(100, 110, 220, 40);

        combo.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        combo.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Classique", "Mars", "Nature", "Planet" }));
        jPanel5.add(combo);
        combo.setBounds(100, 60, 220, 40);

        panel1.add(jPanel5);
        jPanel5.setBounds(330, 290, 450, 160);

        getContentPane().add(panel1);
        panel1.setBounds(0, 0, 780, 460);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel adresse;
    private javax.swing.JLabel cin;
    private javax.swing.JComboBox combo;
    private javax.swing.JLabel diplome;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel16;
    private javax.swing.JPanel jPanel17;
    private javax.swing.JPanel jPanel18;
    private javax.swing.JPanel jPanel19;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTextField login;
    private javax.swing.JPasswordField newPassword;
    private javax.swing.JLabel nom;
    private javax.swing.JPasswordField oldPassword;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JLabel prenom;
    private javax.swing.JButton validerPassword;
    private javax.swing.JButton validerTheme;
    // End of variables declaration//GEN-END:variables
}
