/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package view.Administrateur;

import static java.awt.Cursor.DEFAULT_CURSOR;
import static java.awt.EventQueue.invokeLater;
import static java.util.logging.Level.SEVERE;
import static java.util.logging.Logger.getLogger;
import static javax.swing.BorderFactory.createLineBorder;
import static javax.swing.BorderFactory.createTitledBorder;
import static javax.swing.UIManager.getInstalledLookAndFeels;
import static javax.swing.UIManager.setLookAndFeel;

/**
 *
 * @author Hachem
 */
public class NewJFrame extends javax.swing.JFrame {

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        label8 = new javax.swing.JLabel();
        t8 = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        label2 = new javax.swing.JLabel();
        t2 = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        label3 = new javax.swing.JLabel();
        t3 = new javax.swing.JTextField();
        jPanel8 = new javax.swing.JPanel();
        label4 = new javax.swing.JLabel();
        t4 = new javax.swing.JTextField();
        jPanel9 = new javax.swing.JPanel();
        label5 = new javax.swing.JLabel();
        t5 = new javax.swing.JTextField();
        jPanel10 = new javax.swing.JPanel();
        label6 = new javax.swing.JLabel();
        t6 = new javax.swing.JTextField();
        jPanel11 = new javax.swing.JPanel();
        label7 = new javax.swing.JLabel();
        t7 = new javax.swing.JTextField();
        jPanel12 = new javax.swing.JPanel();
        label1 = new javax.swing.JLabel();
        t1 = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        table = new javax.swing.JTable();
        panel1 = new javax.swing.JPanel();
        deconecter = new javax.swing.JButton();
        retour = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jButton2 = new javax.swing.JButton();
        supprimer = new javax.swing.JButton();
        ajouter = new javax.swing.JButton();
        annuler = new javax.swing.JButton();
        modifier = new javax.swing.JButton();
        panel2 = new javax.swing.JPanel();
        titre = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        panel3.setBackground(new java.awt.Color(153, 255, 102));
        panel3.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(255, 255, 255));
        jPanel4.setForeground(new java.awt.Color(255, 102, 0));
        jPanel4.setLayout(null);

        label8.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label8.setText("L8");
        jPanel4.add(label8);
        label8.setBounds(0, 0, 130, 30);

        panel3.add(jPanel4);
        jPanel4.setBounds(10, 290, 170, 30);
        panel3.add(t8);
        t8.setBounds(200, 290, 170, 30);

        jPanel6.setBackground(new java.awt.Color(255, 255, 255));
        jPanel6.setForeground(new java.awt.Color(255, 102, 0));
        jPanel6.setLayout(null);

        label2.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label2.setText("L2");
        jPanel6.add(label2);
        label2.setBounds(0, 0, 130, 30);

        panel3.add(jPanel6);
        jPanel6.setBounds(10, 50, 170, 30);
        panel3.add(t2);
        t2.setBounds(200, 50, 170, 30);

        jPanel7.setBackground(new java.awt.Color(255, 255, 255));
        jPanel7.setForeground(new java.awt.Color(255, 102, 0));
        jPanel7.setLayout(null);

        label3.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label3.setText("L3");
        jPanel7.add(label3);
        label3.setBounds(0, 0, 130, 30);

        panel3.add(jPanel7);
        jPanel7.setBounds(10, 90, 170, 30);
        panel3.add(t3);
        t3.setBounds(200, 90, 170, 30);

        jPanel8.setBackground(new java.awt.Color(255, 255, 255));
        jPanel8.setForeground(new java.awt.Color(255, 102, 0));
        jPanel8.setLayout(null);

        label4.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label4.setText("L4");
        jPanel8.add(label4);
        label4.setBounds(0, 0, 130, 30);

        panel3.add(jPanel8);
        jPanel8.setBounds(10, 130, 170, 30);
        panel3.add(t4);
        t4.setBounds(200, 130, 170, 30);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setForeground(new java.awt.Color(255, 102, 0));
        jPanel9.setLayout(null);

        label5.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label5.setText("L5");
        jPanel9.add(label5);
        label5.setBounds(0, 0, 130, 30);

        panel3.add(jPanel9);
        jPanel9.setBounds(10, 170, 170, 30);
        panel3.add(t5);
        t5.setBounds(200, 170, 170, 30);

        jPanel10.setBackground(new java.awt.Color(255, 255, 255));
        jPanel10.setForeground(new java.awt.Color(255, 102, 0));
        jPanel10.setLayout(null);

        label6.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label6.setText("L6");
        jPanel10.add(label6);
        label6.setBounds(0, 0, 130, 30);

        panel3.add(jPanel10);
        jPanel10.setBounds(10, 210, 170, 30);
        panel3.add(t6);
        t6.setBounds(200, 210, 170, 30);

        jPanel11.setBackground(new java.awt.Color(255, 255, 255));
        jPanel11.setForeground(new java.awt.Color(255, 102, 0));
        jPanel11.setLayout(null);

        label7.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label7.setText("L7");
        jPanel11.add(label7);
        label7.setBounds(0, 0, 130, 30);

        panel3.add(jPanel11);
        jPanel11.setBounds(10, 250, 170, 30);
        panel3.add(t7);
        t7.setBounds(200, 250, 170, 30);

        jPanel12.setBackground(new java.awt.Color(255, 255, 255));
        jPanel12.setForeground(new java.awt.Color(255, 102, 0));
        jPanel12.setLayout(null);

        label1.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        label1.setText("L1");
        jPanel12.add(label1);
        label1.setBounds(0, 0, 130, 30);

        panel3.add(jPanel12);
        jPanel12.setBounds(10, 10, 170, 30);
        panel3.add(t1);
        t1.setBounds(200, 10, 170, 30);

        getContentPane().add(panel3);
        panel3.setBounds(10, 150, 380, 350);

        table.setBackground(new java.awt.Color(0, 0, 0));
        table.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(255, 255, 255)));
        table.setFont(new java.awt.Font("Yu Gothic Light", 0, 18)); // NOI18N
        table.setForeground(new java.awt.Color(255, 255, 255));
        table.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {"sc", "sqfqfq", "fqsff", "qsf"},
                {"sqqcq", "sqsqfq", "qsfqsfq", "fqsfqsf"},
                {"qsf", "qsfsqfq", "qsfqsfqs", null},
                {null, "qsf", "qsff", "qsff"}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        table.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        table.setGridColor(new java.awt.Color(255, 255, 255));
        table.setRowHeight(30);
        table.setRowMargin(2);
        table.setSelectionBackground(new java.awt.Color(255, 255, 255));
        table.setSelectionForeground(new java.awt.Color(0, 0, 0));
        jScrollPane1.setViewportView(table);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(400, 100, 600, 402);

        panel1.setBackground(new java.awt.Color(51, 255, 204));
        panel1.setLayout(null);

        deconecter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img1/deconnecter.png"))); // NOI18N
        panel1.add(deconecter);
        deconecter.setBounds(80, 10, 60, 60);

        retour.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img1/retour.png"))); // NOI18N
        panel1.add(retour);
        retour.setBounds(10, 10, 60, 60);

        getContentPane().add(panel1);
        panel1.setBounds(10, 10, 990, 80);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        jPanel2.setLayout(null);

        jButton2.setText("jButton1");
        jPanel2.add(jButton2);
        jButton2.setBounds(30, 230, 73, 23);

        supprimer.setBackground(new java.awt.Color(204, 204, 255));
        supprimer.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        supprimer.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img3/inscrire.png"))); // NOI18N
        supprimer.setText("Supprimer");
        supprimer.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(supprimer);
        supprimer.setBounds(370, 10, 200, 60);

        ajouter.setBackground(new java.awt.Color(204, 204, 255));
        ajouter.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        ajouter.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img3/inscrire.png"))); // NOI18N
        ajouter.setText("Ajouter");
        ajouter.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(ajouter);
        ajouter.setBounds(10, 10, 170, 60);

        annuler.setBackground(new java.awt.Color(204, 204, 255));
        annuler.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        annuler.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img3/inscrire.png"))); // NOI18N
        annuler.setText("Annuler");
        annuler.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(annuler);
        annuler.setBounds(580, 10, 170, 60);

        modifier.setBackground(new java.awt.Color(204, 204, 255));
        modifier.setFont(new java.awt.Font("Yu Gothic Light", 0, 24)); // NOI18N
        modifier.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/img3/inscrire.png"))); // NOI18N
        modifier.setText("Modifier");
        modifier.setBorder(javax.swing.BorderFactory.createTitledBorder(""));
        jPanel2.add(modifier);
        modifier.setBounds(190, 10, 170, 60);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(10, 510, 990, 80);

        panel2.setBackground(new java.awt.Color(255, 102, 0));
        panel2.setForeground(new java.awt.Color(255, 102, 0));
        panel2.setLayout(null);

        titre.setFont(new java.awt.Font("Yu Gothic Light", 1, 24)); // NOI18N
        titre.setText("L1");
        panel2.add(titre);
        titre.setBounds(10, 10, 170, 30);

        getContentPane().add(panel2);
        panel2.setBounds(10, 100, 380, 50);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton ajouter;
    private javax.swing.JButton annuler;
    private javax.swing.JButton deconecter;
    private javax.swing.JButton jButton2;
    private javax.swing.JPanel jPanel10;
    private javax.swing.JPanel jPanel11;
    private javax.swing.JPanel jPanel12;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel label1;
    private javax.swing.JLabel label2;
    private javax.swing.JLabel label3;
    private javax.swing.JLabel label4;
    private javax.swing.JLabel label5;
    private javax.swing.JLabel label6;
    private javax.swing.JLabel label7;
    private javax.swing.JLabel label8;
    private javax.swing.JButton modifier;
    private javax.swing.JPanel panel1;
    private javax.swing.JPanel panel2;
    private javax.swing.JPanel panel3;
    private javax.swing.JButton retour;
    private javax.swing.JButton supprimer;
    private javax.swing.JTextField t1;
    private javax.swing.JTextField t2;
    private javax.swing.JTextField t3;
    private javax.swing.JTextField t4;
    private javax.swing.JTextField t5;
    private javax.swing.JTextField t6;
    private javax.swing.JTextField t7;
    private javax.swing.JTextField t8;
    private javax.swing.JTable table;
    private javax.swing.JLabel titre;
    // End of variables declaration//GEN-END:variables
}
